// src/components/config/GeneralSettings.vue
<script setup lang="ts">
  import type { Config, ShellType } from '@/services/cmd';

  defineProps<{
    config: Config;
  }>();

  const emit = defineEmits<{
    update: [key: string, value: unknown];
  }>();

  const logLevelOptions = ['error', 'warn', 'info', 'debug', 'trace'];

  const shellOptions: { label: string; value: ShellType }[] = [
    { label: '自动检测', value: 'auto' },
    { label: 'Cmd', value: 'cmd' },
    { label: 'PowerShell', value: 'powershell' },
    { label: 'Bash', value: 'bash' },
  ];

  const themeOptions = [
    { label: '深色', value: 'dark' },
    { label: '浅色', value: 'light' },
  ];

  const homeRouteOptions = [
    { label: '导航', value: 'overview' },
    { label: '配置', value: 'config' },
  ];

  function updateLogLevel(value: string) {
    emit('update', 'log_level', value);
  }

  function updateHome(value: string) {
    emit('update', 'frontend.home', value);
  }

  function updateShell(value: string) {
    emit('update', 'shell', value);
  }

  function updateMode(value: string) {
    emit('update', 'frontend.mode', value);
  }
</script>

<template>
  <div class="general-settings">
    <h2 class="section-title">通用</h2>

    <div class="setting-group">
      <div class="setting-item">
        <div class="setting-info">
          <div class="setting-label">日志级别</div>
          <div class="setting-desc">控制应用日志输出级别</div>
        </div>
        <el-select
          :model-value="config.log_level"
          placeholder="选择日志级别"
          style="width: 160px"
          @update:model-value="updateLogLevel"
        >
          <el-option v-for="level in logLevelOptions" :key="level" :label="level" :value="level" />
        </el-select>
      </div>

      <div class="setting-item">
        <div class="setting-info">
          <div class="setting-label">首页路由</div>
          <div class="setting-desc">应用启动时跳转的页面</div>
        </div>
        <el-select
          :model-value="config.frontend.home"
          placeholder="选择首页"
          style="width: 160px"
          @update:model-value="updateHome"
        >
          <el-option
            v-for="option in homeRouteOptions"
            :key="option.value"
            :label="option.label"
            :value="option.value"
          />
        </el-select>
      </div>

      <div class="setting-item">
        <div class="setting-info">
          <div class="setting-label">主题模式</div>
          <div class="setting-desc">切换深色或浅色主题</div>
        </div>
        <el-select
          :model-value="config.frontend.mode"
          style="width: 160px"
          @update:model-value="updateMode"
        >
          <el-option
            v-for="option in themeOptions"
            :key="option.value"
            :label="option.label"
            :value="option.value"
          />
        </el-select>
      </div>

      <div class="setting-item">
        <div class="setting-info">
          <div class="setting-label">Shell 类型</div>
          <div class="setting-desc">MCP 服务器使用的 Shell 环境</div>
        </div>
        <el-select
          :model-value="config.shell"
          style="width: 160px"
          @update:model-value="updateShell"
        >
          <el-option
            v-for="option in shellOptions"
            :key="option.value"
            :label="option.label"
            :value="option.value"
          />
        </el-select>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
  .section-title {
    font-size: 1.25rem;
    font-weight: 600;
    color: var(--text-primary);
    margin: 0 0 1.5rem 0;
  }

  .setting-group {
    background: var(--bg-tertiary);
    border-radius: 12px;
    border: 1px solid var(--border-default);
    overflow: hidden;
  }

  .setting-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem 1.25rem;

    & + .setting-item {
      border-top: 1px solid var(--border-default);
    }
  }

  .setting-info {
    flex: 1;
    margin-right: 1rem;
  }

  .setting-label {
    font-size: 0.9375rem;
    color: var(--text-primary);
  }

  .setting-desc {
    font-size: 0.8125rem;
    color: var(--text-tertiary);
    margin-top: 0.25rem;
  }
</style>

// src/components/config/GeneralSettings.tsx
import { cn } from '@/lib/utils';
import { useConfig } from '@/hooks/useConfig';
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { Config, LogLevel, ShellType } from '@/schemas/config';

const LOG_LEVEL_OPTIONS: { value: LogLevel; label: string }[] = [
  { value: 'error', label: 'Error' },
  { value: 'warn', label: 'Warn' },
  { value: 'info', label: 'Info' },
  { value: 'debug', label: 'Debug' },
  { value: 'trace', label: 'Trace' },
];

const HOME_OPTIONS: { value: Config['frontend']['home']; label: string }[] = [
  { value: 'overview', label: '导航' },
  { value: 'config', label: '配置' },
];

const MODE_OPTIONS: { value: Config['frontend']['mode']; label: string }[] = [
  { value: 'dark', label: '深色' },
  { value: 'light', label: '浅色' },
];

const SHELL_OPTIONS: { value: ShellType; label: string }[] = [
  { value: 'auto', label: 'Auto' },
  { value: 'cmd', label: 'CMD' },
  { value: 'powershell', label: 'PowerShell' },
  { value: 'bash', label: 'Bash' },
];

export default function GeneralSettings() {
  const { config, updateLogLevel, updateHome, updateMode, updateShell } = useConfig();

  if (!config) {
    return null;
  }

  return (
    <div className="flex flex-col gap-4 p-4">
      <Card>
        <CardHeader>
          <CardTitle>通用设置</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <SettingRow label="日志级别">
            <Select value={config.log_level} onValueChange={(v) => updateLogLevel(v as LogLevel)}>
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectLabel>日志级别</SelectLabel>
                  {LOG_LEVEL_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </SettingRow>

          <SettingRow label="首页路由">
            <Select
              value={config.frontend.home}
              onValueChange={(v) => updateHome(v as Config['frontend']['home'])}
            >
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectLabel>首页路由</SelectLabel>
                  {HOME_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </SettingRow>

          <SettingRow label="主题模式">
            <Select
              value={config.frontend.mode}
              onValueChange={(v) => updateMode(v as Config['frontend']['mode'])}
            >
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectLabel>主题模式</SelectLabel>
                  {MODE_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </SettingRow>

          <SettingRow label="Shell 类型">
            <Select value={config.shell} onValueChange={(v) => updateShell(v as ShellType)}>
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectLabel>Shell 类型</SelectLabel>
                  {SHELL_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectGroup>
              </SelectContent>
            </Select>
          </SettingRow>
        </CardContent>
      </Card>
    </div>
  );
}

function SettingRow({
  label,
  className,
  children,
}: {
  label: string;
  className?: string;
  children: React.ReactNode;
}) {
  return (
    <div className={cn('flex items-center justify-between', className)}>
      <span className="text-sm text-muted-foreground">{label}</span>
      {children}
    </div>
  );
}
