// src/routes/overview.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { Settings, Activity } from 'lucide-react';
import { useAppStore } from '@/store/app';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const apps = [
  {
    id: 'config',
    title: '配置',
    description: '日志级别、首页、主题、MCP 服务器管理',
    icon: Settings,
    route: '/config',
  },
  {
    id: 'mcp-panel',
    title: 'MCP 面板',
    description: '查看 MCP 服务器工具、提示、资源',
    icon: Activity,
    route: '/mcp-panel',
  },
] as const;

export const Route = createFileRoute('/overview')({
  component: OverviewComponent,
});

function OverviewComponent() {
  const navigate = useNavigate();
  const addTab = useAppStore((s) => s.addTab);
  const setActiveTab = useAppStore((s) => s.setActiveTab);

  function handleAppClick(app: (typeof apps)[number]) {
    addTab({ title: app.title, closable: true, route: app.route });
    setActiveTab(app.route);
    navigate({ to: app.route });
  }

  return (
    <div className="flex flex-col gap-6 p-6">
      <h1 className="text-2xl font-bold">导航</h1>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {apps.map((app) => {
          const Icon = app.icon;
          return (
            <Card
              key={app.id}
              className="cursor-pointer transition-colors hover:bg-muted/50"
              onClick={() => handleAppClick(app)}
            >
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Icon className="size-5" />
                  {app.title}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">{app.description}</p>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}

// src/pages/overview.vue
<script setup lang="ts">
  import { ref, onMounted } from 'vue';
  import { useRouter } from 'vue-router';
  import { getConfig, type Config } from '@/services/cmd';
  import { useAppStore } from '@/stores/app';

  const router = useRouter();
  const store = useAppStore();
  const config = ref<Config | null>(null);
  const loading = ref(true);

  onMounted(async () => {
    try {
      config.value = await getConfig();
    } finally {
      loading.value = false;
    }
  });

  interface AppItem {
    id: string;
    name: string;
    icon: string;
    color: string;
    route: string;
  }

  const apps = ref<AppItem[]>([
    { id: 'config', name: '配置', icon: '⚙', color: '#6366f1', route: '/config' },
    { id: 'mcp-panel', name: 'MCP 面板', icon: '🔌', color: '#10b981', route: '/mcp-panel' },
  ]);

  function handleAppClick(app: AppItem) {
    if (app.id === 'config') {
      store.setActiveTab('config');
      router.push(app.route);
    } else {
      store.addTab({ title: app.name, closable: true, route: app.route });
      router.push(app.route);
    }
  }
</script>

<template>
  <div v-loading="loading" class="overview-page">
    <main class="overview-main">
      <h2 class="section-title">应用</h2>
      <div class="app-grid">
        <div v-for="app in apps" :key="app.id" class="app-item" @click="handleAppClick(app)">
          <div class="app-icon" :style="{ backgroundColor: app.color }">
            <span class="icon-text">{{ app.icon }}</span>
          </div>
          <span class="app-name">{{ app.name }}</span>
        </div>
      </div>
    </main>
  </div>
</template>

<style scoped lang="scss">
  .overview-page {
    min-height: 100vh;
    background: var(--bg-secondary);
    color: var(--text-primary);
  }

  .overview-main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
  }

  .section-title {
    font-size: 1.125rem;
    font-weight: 500;
    margin-bottom: 1.5rem;
    color: var(--text-primary);
  }

  .app-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(80px, 1fr));
    gap: 1.5rem;
    justify-items: start;
  }

  .app-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    cursor: pointer;
    transition: transform 0.2s;

    &:hover {
      transform: scale(1.05);
    }
  }

  .app-icon {
    width: 56px;
    height: 56px;
    border-radius: 14px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: box-shadow 0.2s;

    &:hover {
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
    }
  }

  .icon-text {
    font-size: 1.5rem;
    color: #fff;
    font-weight: 500;
  }

  .app-name {
    font-size: 0.75rem;
    color: var(--text-secondary);
    text-align: center;
    white-space: nowrap;
  }

  @media (max-width: 768px) {
    .overview-main {
      padding: 1rem;
    }

    .app-grid {
      grid-template-columns: repeat(4, 1fr);
      gap: 1rem;
    }

    .app-icon {
      width: 48px;
      height: 48px;
      border-radius: 12px;
    }

    .icon-text {
      font-size: 1.25rem;
    }
  }
</style>
